# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Logs reporting time')),
                ('log_text', models.TextField()),
                ('level', models.CharField(help_text='Importance of the logline', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PluginApp',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LogsHandler.Equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='LogsHandler.Equipment')),
            ],
            bases=('LogsHandler.equipment',),
        ),
        migrations.AddField(
            model_name='logline',
            name='pluin_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to='LogsHandler.PluginApp'),
        ),
    ]
