# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logline',
            old_name='level',
            new_name='importance',
        ),
        migrations.AddField(
            model_name='logline',
            name='slibling',
            field=models.ManyToManyField(related_name='_logline_slibling_+', to='LogsHandler.Logline'),
        ),
    ]
