# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0002_auto_20160503_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='logline',
            name='next',
            field=models.ManyToManyField(related_name='_logline_next_+', to='LogsHandler.Logline'),
        ),
        migrations.AddField(
            model_name='logline',
            name='previous',
            field=models.ManyToManyField(related_name='_logline_previous_+', to='LogsHandler.Logline'),
        ),
    ]
