# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0003_auto_20160503_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('execution_date', models.DateTimeField()),
                ('execution_state', models.IntegerField()),
                ('test_case_flag', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='logline',
            old_name='pluin_app',
            new_name='app',
        ),
        migrations.RemoveField(
            model_name='logline',
            name='next',
        ),
        migrations.RemoveField(
            model_name='logline',
            name='previous',
        ),
        migrations.AddField(
            model_name='logline',
            name='next_logs',
            field=models.ManyToManyField(related_name='_logline_next_logs_+', to='LogsHandler.Logline'),
        ),
        migrations.AddField(
            model_name='logline',
            name='previous_logs',
            field=models.ManyToManyField(related_name='_logline_previous_logs_+', to='LogsHandler.Logline'),
        ),
        migrations.AlterField(
            model_name='logline',
            name='timestamp',
            field=models.DateTimeField(verbose_name=b'Logs_reporting_time'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='testrun',
            field=models.ManyToManyField(related_name='equipments', to='LogsHandler.TestRun'),
        ),
    ]
