# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0004_auto_20160510_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_tag',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
