# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0006_auto_20160510_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='logline',
            name='testrun',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to='LogsHandler.TestRun'),
        ),
    ]
