# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0007_logline_testrun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEvent',
        ),
    ]
