# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0008_delete_logevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginapp',
            name='equipment_ptr',
        ),
        migrations.RemoveField(
            model_name='pluginapp',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='logline',
            name='app',
        ),
        migrations.DeleteModel(
            name='PluginApp',
        ),
    ]
