# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0009_auto_20160510_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logline',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='logline',
            name='timestamp',
        ),
    ]
