# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0010_auto_20160510_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logline',
            name='next_logs',
        ),
        migrations.RemoveField(
            model_name='logline',
            name='previous_logs',
        ),
        migrations.RemoveField(
            model_name='logline',
            name='slibling',
        ),
    ]
