# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0011_auto_20160510_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='testrun',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
