# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0012_auto_20160510_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='test_case_tempalte',
            field=models.TextField(default=None),
        ),
    ]
