# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0013_testrun_test_case_tempalte'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('tempalte', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='execution_date',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='execution_state',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='test_case_flag',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='test_case_tempalte',
        ),
        migrations.AddField(
            model_name='testrun',
            name='logevents_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LogsHandler.LogEvents'),
            preserve_default=False,
        ),
    ]
