# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0015_auto_20160510_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='testrun_case_link',
            field=models.URLField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='testrun',
            name='testrun_result',
            field=models.CharField(default=b'Failed', max_length=15),
        ),
    ]
