# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0016_auto_20160510_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logline',
            name='log_text',
            field=models.TextField(default=None),
        ),
    ]
