# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LogsHandler', '0018_auto_20160510_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField(default=None)),
                ('testrun', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to='LogsHandler.TestRun')),
            ],
        ),
    ]
